function scenario = validateScenario(scenario)
%VALIDATESCENARIO Validate the experiment configuration before a run.
%
% Internal simulation helpers trust this one outer boundary. Keep this check
% focused on fields that define the checkpoint-one experiment contract.

required = {'Name', 'Time', 'Observer', 'Follower', 'Base', 'Obstacles', ...
    'Sensor', 'Estimator', 'Playback'};
if ~isstruct(scenario) || ~all(isfield(scenario, required))
    error('simulation:validateScenario:InvalidScenario', ...
        'scenario must contain the checkpoint-one configuration fields.');
end

% Time alignment makes every held input and logged sample deterministic.
time = scenario.Time;
if ~isstruct(time) || ~all(isfield(time, {'Start', 'Stop', 'Step'})) || ...
        ~isFiniteScalar(time.Start) || ~isFiniteScalar(time.Stop) || ...
        ~isFiniteScalar(time.Step) || ...
        time.Stop <= time.Start || time.Step <= 0
    error('simulation:validateScenario:InvalidTime', ...
        'Time must contain finite Start, Stop, and positive Step values.');
end
intervals = (time.Stop - time.Start) / time.Step;
if abs(intervals - round(intervals)) > 128 * eps(max(1, abs(intervals)))
    error('simulation:validateScenario:UnalignedTime', ...
        '(Stop-Start)/Step must be integral.');
end

% Validate both agent schedules before the runner assumes trusted shapes.
validateAgent(scenario.Observer, true, 'Observer');
validateAgent(scenario.Follower, false, 'Follower');
validateReference(scenario.Observer.Reference, time, 'Observer');
validateReference(scenario.Follower.Reference, time, 'Follower');

% Static geometry and base position are shared across all logged samples.
if ~(isnumeric(scenario.Base.Position) && isreal(scenario.Base.Position) && ...
        numel(scenario.Base.Position) == 2 && ...
        all(isfinite(scenario.Base.Position(:))))
    error('simulation:validateScenario:InvalidPosition', ...
        'Base.Position must contain two finite values.');
end
if ~isempty(scenario.Obstacles) && (~isstruct(scenario.Obstacles) || ...
        ~isfield(scenario.Obstacles, 'Vertices'))
    error('simulation:validateScenario:InvalidObstacles', ...
        'Obstacles must be polygon obstacle structs.');
end
for obstacleIndex = 1:numel(scenario.Obstacles)
    vertices = scenario.Obstacles(obstacleIndex).Vertices;
    if ~(isnumeric(vertices) && isreal(vertices) && size(vertices, 2) == 2 && ...
            size(vertices, 1) >= 3 && all(isfinite(vertices(:))))
        error('simulation:validateScenario:InvalidObstacles', ...
            'Obstacle vertices must be finite N-by-2 polygons with N >= 3.');
    end
end

% Sensor settings define the fixed scan grid and local random stream behavior.
sensor = scenario.Sensor;
if ~isstruct(sensor) || ~isfield(sensor, 'NumRays') || ...
        ~isFiniteScalar(sensor.NumRays) || sensor.NumRays < 2 || ...
        sensor.NumRays ~= floor(sensor.NumRays)
    error('simulation:validateScenario:InvalidSensor', ...
        'Sensor.NumRays must be an integer greater than or equal to two.');
end
if isfield(sensor, 'RangeNoiseStd') && ...
        (~isFiniteScalar(sensor.RangeNoiseStd) || ...
        sensor.RangeNoiseStd < 0)
    error('simulation:validateScenario:InvalidSensor', ...
        'Sensor.RangeNoiseStd must be finite and nonnegative.');
end
if isfield(sensor, 'Seed') && (~isFiniteScalar(sensor.Seed) || ...
        sensor.Seed < 0 || sensor.Seed > 2^32 - 1 || sensor.Seed ~= floor(sensor.Seed))
    error('simulation:validateScenario:InvalidSensor', ...
        'Sensor.Seed must be an integer in the RandStream range.');
end
if isfield(sensor, 'Tolerance') && (~isFiniteScalar(sensor.Tolerance) || ...
        sensor.Tolerance <= 0)
    error('simulation:validateScenario:InvalidSensor', ...
        'Sensor.Tolerance must be finite and positive.');
end

% Estimators expose the complete causal lifecycle as three callbacks.
callbacks = {'Initialize', 'Predict', 'Correct'};
if ~isstruct(scenario.Estimator) || ...
        ~all(isfield(scenario.Estimator, callbacks)) || ...
        ~all(cellfun(@(name) isa(scenario.Estimator.(name), 'function_handle'), callbacks))
    error('simulation:validateScenario:InvalidEstimator', ...
        'Estimator must provide Initialize, Predict, and Correct callbacks.');
end

% Playback is rendering-only configuration, but keep its bounds well-defined.
playback = scenario.Playback;
if ~isstruct(playback) || ~all(isfield(playback, {'Bounds', 'FrameRate', 'Speed'})) || ...
        ~isnumeric(playback.Bounds) || numel(playback.Bounds) ~= 4 || ...
        ~isreal(playback.Bounds) || any(~isfinite(playback.Bounds(:))) || ...
        ~isFiniteScalar(playback.FrameRate) || ~isFiniteScalar(playback.Speed) || ...
        playback.Bounds(1) >= playback.Bounds(2) || ...
        playback.Bounds(3) >= playback.Bounds(4) || playback.FrameRate <= 0 || ...
        playback.Speed <= 0
    error('simulation:validateScenario:InvalidPlayback', ...
        'Playback must define bounds, positive frame rate, and positive speed.');
end
end

function validateAgent(agent, requiresFov, name)
if ~isstruct(agent) || ~isfield(agent, 'InitialPose') || ~isfield(agent, 'Reference') || ...
        ~isnumeric(agent.InitialPose) || ~isreal(agent.InitialPose) || ...
        numel(agent.InitialPose) ~= 3 || ...
        any(~isfinite(agent.InitialPose(:)))
    error('simulation:validateScenario:InvalidAgent', ...
        '%s must define a finite initial pose and reference.', name);
end
if requiresFov && (~isfield(agent, 'Fov') || ~isa(agent.Fov, 'fov.FovSpec') || ...
        ~isfield(agent, 'Policy') || ~isa(agent.Policy, 'function_handle'))
    error('simulation:validateScenario:InvalidAgent', ...
        'Observer must define Fov and Policy.');
end
end

function validateReference(reference, time, name)
%VALIDATEREFERENCE Enforce zero-order-held breakpoints on the simulation grid.

if ~isstruct(reference) || ~all(isfield(reference, {'Times', 'Values'})) || ...
        ~isnumeric(reference.Times) || ~isreal(reference.Times) || ...
        ~isvector(reference.Times) || isempty(reference.Times) || ...
        ~isnumeric(reference.Values) || ~isreal(reference.Values) || ...
        size(reference.Values, 1) ~= numel(reference.Times) || ...
        size(reference.Values, 2) ~= 3 || any(~isfinite(reference.Times(:))) || ...
        any(~isfinite(reference.Values(:))) || any(diff(reference.Times(:)) <= 0)
    error('simulation:validateScenario:InvalidReference', ...
        '%s.Reference must be an increasing finite N-by-3 schedule.', name);
end
if abs(reference.Times(1) - time.Start) > 128 * eps(max(1, abs(time.Start))) || ...
        reference.Times(end) > time.Stop + 128 * eps(max(1, abs(time.Stop)))
    error('simulation:validateScenario:InvalidReference', ...
        '%s.Reference must start at Time.Start and stay within Time.Stop.', name);
end
indices = (reference.Times(:) - time.Start) / time.Step;
if any(abs(indices - round(indices)) > 128 * eps(max(1, max(abs(indices)))))
    error('simulation:validateScenario:UnalignedReference', ...
        '%s.Reference breakpoints must align with Time.Step.', name);
end
end

function result = isFiniteScalar(value)
result = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end
