% Run and visualize the single-wall demonstration scenario.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
run(fullfile(projectRoot, 'startup.m'));

scenario = scenarios.singleWall();
result = fov.castRays( ...
    scenario.Observer, scenario.Obstacles, 'NumRays', scenario.NumRays);

padding = 0.5;
nominalBoundary = result.NominalBoundary;
bounds = [min(nominalBoundary(:, 1)) - padding, ...
    max(nominalBoundary(:, 1)) + padding, ...
    min(nominalBoundary(:, 2)) - padding, ...
    max(nominalBoundary(:, 2)) + padding];

signedDistance = @(points) metrics.signedEuclideanDistance( ...
    result.VisibleBoundary, points, 'Tolerance', result.Tolerance);
field = metrics.sampleField(signedDistance, ...
    'Bounds', bounds, ...
    'GridSize', [241, 241], ...
    'Name', 'Signed Euclidean distance', ...
    'Units', 'coordinate units');

[~, axesHandle] = viz.plotScenario(scenario, result, ...
    'ShowRays', false, ...
    'ShowNominalFov', true, ...
    'ShowHitPoints', false, ...
    'MetricField', field, ...
    'MetricContourLevels', -5:0.5:5);
title(axesHandle, sprintf('%s: signed Euclidean distance (negative inside)', ...
    char(scenario.Name)));
